# [x] Make a debug menu class
# [ ] Make a story menu class
# [ ] Accesss story text

import random
import sys

from Counter import Counter
from Interactable import Interactable
from Location import Location
from Player import Player
from Trait import Trait
from Traversal import Traversal
from DebugMenu import DebugMenu
from DisplayText import displayText

# Initialize the game's values

player = Player()
player.travels.setupTraversal()

player.traitDictionary.update({"Bold":Trait("Bold", "Bold",False)})
player.traitDictionary.update({"Brave":Trait("Brave", "Brave",False)})
player.traitDictionary.update({"Competent":Trait("Competent", "Competent",False)})
player.traitDictionary.update({"Contientious":Trait("Contientious", "Contientious",False)})
player.traitDictionary.update({"Curious":Trait("Curious", "Curious",False)})
player.traitDictionary.update({"Daring":Trait("Daring", "Daring",False)})
player.traitDictionary.update({"Dutiful":Trait("Dutiful", "Dutiful",False)})
player.traitDictionary.update({"Fearless":Trait("Fearless", "Fearless",False)})
player.traitDictionary.update({"Impulsive":Trait("Impulsive", "Impulsive",False)})
player.traitDictionary.update({"Inquisitive":Trait("Inquisitive", "Inquisitive",False)})
player.traitDictionary.update({"Passionate":Trait("Passionate", "Passionate",False)})
player.traitDictionary.update({"Private":Trait("Private", "Private",False)})
player.traitDictionary.update({"Proud":Trait("Proud", "Proud",False)})
player.traitDictionary.update({"Sentimental":Trait("Sentimental", "Sentimental",False)})
player.traitDictionary.update({"Trepidatious":Trait("Trepidatious", "Trepidatious",False)})
player.traitDictionary.update({"Start" : Trait("Start", "Start",True)})
player.traitDictionary.update({"Hub" : Trait("Hub", "Hub",True)})

player.counterDictionary.update({"Castle":Counter("Castle","Castle",0)})
player.counterDictionary.update({"Feral":Counter("Feral","Feral",0)})
player.counterDictionary.update({"Past":Counter("Past","Past",0)})
player.counterDictionary.update({"Seek":Counter("Seek","Seek",0)})
player.counterDictionary.update({"Town":Counter("Town","Town",0)})

player.travels.locationDictionary.update({"Hub" : Location("Hub","Central Location","Hub")})
player.travels.locationDictionary.update({"Start" : Location("Start","Starting Location","Start")})
player.travels.locationDictionary.update({"BooksStart" : Location("BooksStart","Pack only books","Start")})
player.travels.locationDictionary.update({"CookwareStart" : Location("CookwareStart","Pack only cookware","Start")})
player.travels.locationDictionary.update({"KeepsakesStart" : Location("KeepsakesStart","Pack only keepsakes","Start")})
player.travels.locationDictionary.update({"NoPackingStart" : Location("NoPackingStart","Don't pack; just leave","Start")})
player.travels.locationDictionary.update({"PatienceStart" : Location("PatienceStart","Ask for patience","Start")})
player.travels.locationDictionary.update({"AdminBedroom" : Location("AdminBedroom","Town Administrator Bedroom","Inquisitive")})
player.travels.locationDictionary.update({"Apiary" : Location("Apiary","Apiary and Sericulture Hut","Inquisitive")})
player.travels.locationDictionary.update({"AquacultureBuilding" : Location("AquacultureBuilding","Fish Supply House and Hatchery","Trepidatious")})
player.travels.locationDictionary.update({"ArcheryRange" : Location("ArcheryRange","Archery Range","Daring")})
player.travels.locationDictionary.update({"Armory" : Location("Armory","Armor Room","Daring")})
player.travels.locationDictionary.update({"ArtStudio" : Location("ArtStudio","Art Studio","Passionate")})
player.travels.locationDictionary.update({"Cave" : Location("Cave","Cave","Brave")})
player.travels.locationDictionary.update({"DivingPlatform" : Location("DivingPlatform","High Tower with Diving Platform","Fearless")})
player.travels.locationDictionary.update({"FictionLibrary" : Location("FictionLibrary","Fiction Library","Passionate")})
player.travels.locationDictionary.update({"FireplaceLounge" : Location("FireplaceLounge","Fireplace Lounge","Private")})
player.travels.locationDictionary.update({"GallowStage" : Location("GallowStage","Gallows Renovated into a Tiny Stage","Fearless")})
player.travels.locationDictionary.update({"GameRoom" : Location("GameRoom","Casual Games Room","Bold")})
player.travels.locationDictionary.update({"GameYard" : Location("GameYard","Games Yard","Proud")})
player.travels.locationDictionary.update({"Garden" : Location("Garden","Vegetable Garden","Competent")})
player.travels.locationDictionary.update({"HedgeMaze" : Location("HedgeMaze","Hedge Maze","Bold")})
player.travels.locationDictionary.update({"HotSpring" : Location("HotSpring","Hot Spring","Daring")})
player.travels.locationDictionary.update({"HuntersBedroom" : Location("HuntersBedroom","Hunting Bedroom","Brave")})
player.travels.locationDictionary.update({"JewelsBedroom" : Location("JewelsBedroom","Jewels Bedroom","Proud")})
player.travels.locationDictionary.update({"MilitaryGamesRoom" : Location("MilitaryGamesRoom","Military Games Room","Dutiful")})
player.travels.locationDictionary.update({"MusicRoom" : Location("MusicRoom","Music Room","Sentimental")})
player.travels.locationDictionary.update({"NonFictionLibrary" : Location("NonFictionLibrary","NF Library","Inquisitive")})
player.travels.locationDictionary.update({"NookKitchen" : Location("NookKitchen","Nook Kitchen","Private")})
player.travels.locationDictionary.update({"Observatory" : Location("Observatory","Observatory","Curious")})
player.travels.locationDictionary.update({"Orchard" : Location("Orchard","Fruit Orchard","Dutiful")})
player.travels.locationDictionary.update({"PoetryLibrary" : Location("PoetryLibrary","Poetry Library","Sentimental")})
player.travels.locationDictionary.update({"ProductionKitchen" : Location("ProductionKitchen","Production Kitchen","Competent")})
player.travels.locationDictionary.update({"RecipeRoom" : Location("RecipeRoom","Kitchen Recipe Room","Competent")})
player.travels.locationDictionary.update({"SecretPassage" : Location("SecretPassage","Secret Passage behind Bookcase","Curious")})
player.travels.locationDictionary.update({"SpookyBedroom" : Location("SpookyBedroom","Bats and Potions Bedroom","Bold")})
player.travels.locationDictionary.update({"Stables" : Location("Stables","Stables and Coach House","Contientious")})
player.travels.locationDictionary.update({"TreeBedroom" : Location("TreeBedroom","Under the Trees Bedroom","Private")})
player.travels.locationDictionary.update({"UnderwaterBedroom" : Location("UnderwaterBedroom","Underwater Bedroom","Impulsive")})
player.travels.locationDictionary.update({"WineCellar" : Location("WineCellar","Wine and Spirits Cellar","Impulsive")})

player.travels.locationDictionary["BooksStart"].traitNameList.extend(["Passionate","Inquisitive"])
player.travels.locationDictionary["CookwareStart"].traitNameList.extend(["Contientious","Proud"])
player.travels.locationDictionary["KeepsakesStart"].traitNameList.extend(["Private","Sentimental"])
player.travels.locationDictionary["NoPackingStart"].traitNameList.extend(["Brave","Daring","Impulsive"])
player.travels.locationDictionary["PatienceStart"].traitNameList.extend(["Trepidatious","Contientious","Dutiful"])
player.travels.locationDictionary["AdminBedroom"].traitNameList.extend(["Bold"])
player.travels.locationDictionary["Apiary"].traitNameList.extend(["Brave"])
player.travels.locationDictionary["AquacultureBuilding"].traitNameList.extend(["Impulsive"])
player.travels.locationDictionary["ArcheryRange"].traitNameList.extend(["Brave"])
player.travels.locationDictionary["Armory"].traitNameList.extend(["Brave"])
player.travels.locationDictionary["ArtStudio"].traitNameList.extend(["Private","Daring"])
player.travels.locationDictionary["Cave"].traitNameList.extend(["Contientious"])
player.travels.locationDictionary["DivingPlatform"].traitNameList.extend(["Impulsive"])
player.travels.locationDictionary["FictionLibrary"].traitNameList.extend(["Daring"])
player.travels.locationDictionary["FireplaceLounge"].traitNameList.extend(["Dutiful"])
player.travels.locationDictionary["GallowStage"].traitNameList.extend(["Inquisitive","Passionate"])
player.travels.locationDictionary["GameRoom"].traitNameList.extend(["Passionate"])
player.travels.locationDictionary["GameYard"].traitNameList.extend(["Private"])
player.travels.locationDictionary["Garden"].traitNameList.extend(["Proud"])
player.travels.locationDictionary["HedgeMaze"].traitNameList.extend(["Fearless"])
player.travels.locationDictionary["HotSpring"].traitNameList.extend(["Fearless"])
player.travels.locationDictionary["HuntersBedroom"].traitNameList.extend(["Fearless"])
player.travels.locationDictionary["JewelsBedroom"].traitNameList.extend(["Contientious"])
player.travels.locationDictionary["MilitaryGamesRoom"].traitNameList.extend(["Bold","Competent"])
player.travels.locationDictionary["MusicRoom"].traitNameList.extend(["Curious"])
player.travels.locationDictionary["NonFictionLibrary"].traitNameList.extend(["Curious"])
player.travels.locationDictionary["NookKitchen"].traitNameList.extend(["Competent","Daring"])
player.travels.locationDictionary["Observatory"].traitNameList.extend(["Sentimental"])
player.travels.locationDictionary["Orchard"].traitNameList.extend(["Sentimental"])
player.travels.locationDictionary["PoetryLibrary"].traitNameList.extend(["Inquisitive"])
player.travels.locationDictionary["ProductionKitchen"].traitNameList.extend(["Trepidatious"])
player.travels.locationDictionary["RecipeRoom"].traitNameList.extend(["Proud"])
player.travels.locationDictionary["SecretPassage"].traitNameList.extend(["Sentimental"])
player.travels.locationDictionary["SpookyBedroom"].traitNameList.extend(["Trepidatious"])
player.travels.locationDictionary["Stables"].traitNameList.extend(["Proud"])
player.travels.locationDictionary["TreeBedroom"].traitNameList.extend(["Inquisitive"])
player.travels.locationDictionary["UnderwaterBedroom"].traitNameList.extend(["Bold"])
player.travels.locationDictionary["WineCellar"].traitNameList.extend(["Dutiful"])

player.travels.locationDictionary["Stables"].interactablesList.extend([Interactable("caparison","Caparison","Town")])
player.travels.locationDictionary["ArcheryRange"].interactablesList.extend([Interactable("bowAndArrows","Bow and arrows","Feral")])
player.travels.locationDictionary["UnderwaterBedroom"].interactablesList.extend([Interactable("fishSkeletons","Fish skeletons","Feral"), Interactable("stainedCoral","Stained coral","Seek")])
player.travels.locationDictionary["MilitaryGamesRoom"].interactablesList.extend([Interactable("familyTree","Military family tree","Past")])
player.travels.locationDictionary["DivingPlatform"].interactablesList.extend([Interactable("portrait","Portrait","Past")])
player.travels.locationDictionary["Cave"].interactablesList.extend([Interactable("bat","Bat","Feral"), Interactable("townInsignia","Town insignia","Town")])
player.travels.locationDictionary["Orchard"].interactablesList.extend([Interactable("appleCart","Apple cart","Town"), Interactable("berryBasket","Berry basket","Castle")])
player.travels.locationDictionary["Apiary"].interactablesList.extend([Interactable("silkwormCocoons","Silkworm cocoons","Feral")])
player.travels.locationDictionary["SecretPassage"].interactablesList.extend([Interactable("chestOfRobes","Chest of robes","Past")])
player.travels.locationDictionary["WineCellar"].interactablesList.extend([Interactable("yourEmptyHome","Your empty home","Town")])
player.travels.locationDictionary["NookKitchen"].interactablesList.extend([Interactable("spices","Spices","Town"), Interactable("exoticMeat","Exotic meat","Castle")])
player.travels.locationDictionary["AdminBedroom"].interactablesList.extend([Interactable("townLedger","Town ledger","Town")])
player.travels.locationDictionary["ArtStudio"].interactablesList.extend([Interactable("paints","Paints","Seek"), Interactable("lockedChest","Locked chest","Past")])
player.travels.locationDictionary["Garden"].interactablesList.extend([Interactable("labelStakes","Label stakes","Castle"), Interactable("bushel","Bushel","Town")])
player.travels.locationDictionary["GameYard"].interactablesList.extend([Interactable("bucketOfWater","Bucket of water","Castle")])
player.travels.locationDictionary["NonFictionLibrary"].interactablesList.extend([Interactable("mapTome ","Giant tome of world maps","Seek")])
player.travels.locationDictionary["JewelsBedroom"].interactablesList.extend([Interactable("serpentRuby","The Serpent Ruby","Past"), Interactable("bagOfPearls","Bag of pearls","Town")])
player.travels.locationDictionary["MusicRoom"].interactablesList.extend([Interactable("boxOfSheetMusic","Box of sheet music","Town"), Interactable("conductorsScore","Conductor's score","Seek")])
player.travels.locationDictionary["ProductionKitchen"].interactablesList.extend([Interactable("emptyPlates","Empty plates","Seek")])
player.travels.locationDictionary["SpookyBedroom"].interactablesList.extend([Interactable("occultTome","Occult tome","Seek"), Interactable("handwrittenScroll","Scroll with handwritten notes","Past")])
player.travels.locationDictionary["FictionLibrary"].interactablesList.extend([Interactable("contactInfo","Contact information of a publisher","Seek")])
player.travels.locationDictionary["RecipeRoom"].interactablesList.extend([Interactable("recipeBox","Castle recipe box","Seek")])
player.travels.locationDictionary["HedgeMaze"].interactablesList.extend([Interactable("yourClothes","Your own clothing (removed)","Feral")])
player.travels.locationDictionary["PoetryLibrary"].interactablesList.extend([Interactable("wornVolume","Most worn volume","Past")])
player.travels.locationDictionary["GallowStage"].interactablesList.extend([Interactable("trapdoor","Trapdoor","Castle")])
player.travels.locationDictionary["GameRoom"].interactablesList.extend([Interactable("embroideredQuilt","Embroidered quilt","Castle")])
player.travels.locationDictionary["Armory"].interactablesList.extend([Interactable("suitOfArmor","Suit of armor","Feral")])
player.travels.locationDictionary["FireplaceLounge"].interactablesList.extend([Interactable("servingBell","Serving bell","Castle"), Interactable("architecturalPlans","Architectural plans","Seek")])
player.travels.locationDictionary["AquacultureBuilding"].interactablesList.extend([Interactable("preservedFishEggs","Preserved fish eggs","Town"), Interactable("basketOfFish","Basket of adult fish","Castle")])
player.travels.locationDictionary["Observatory"].interactablesList.extend([Interactable("birthCharts","Birth charts","Castle"), Interactable("starMap","Star map with handwriting","Past")])
player.travels.locationDictionary["TreeBedroom"].interactablesList.extend([Interactable("moss","Patch of moss","Seek")])
player.travels.locationDictionary["HuntersBedroom"].interactablesList.extend([Interactable("trophy","Stuffed trophy","Feral")])
player.travels.locationDictionary["HotSpring"].interactablesList.extend([Interactable("giantAnimals","Gigantic animals","Feral"), Interactable("lockets","Princes' lockets","Castle")])

DebugMenu(player)
